//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class install
    {
        public int id { get; set; }
        public System.DateTime registered_on { get; set; }
        public string code { get; set; }
        public bool banned { get; set; }
        public bool temp_ban { get; set; }
        public Nullable<System.DateTime> temp_ban_end { get; set; }
        public System.DateTime last_checkin { get; set; }
        public string username { get; set; }
    }
}
