//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MednaNetAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedLaunchChatEntities : DbContext
    {
        public MedLaunchChatEntities()
            : base("name=MedLaunchChatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<group_members> group_members { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<discord_channels> discord_channels { get; set; }
        public virtual DbSet<discord_messages> discord_messages { get; set; }
        public virtual DbSet<install> installs { get; set; }
    }
}
