//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MednaNetAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discord_channels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public discord_channels()
        {
            this.discord_messages = new HashSet<discord_messages>();
        }
    
        public int id { get; set; }
        public string channel_name { get; set; }
        public string channel_discord_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<discord_messages> discord_messages { get; set; }
    }
}
